# Site Settings
title: Generative AI using Open AI API and Langchain
author:
  name: Utkal Nayak
  email: nayak.utkal@gmail.com

# Build settings
remote_theme: lewismiddleton/cayman-dark
markdown: GFM
